// Generated by CoffeeScript 1.6.3
(function() {
  var Collections, wave_demo;

  Collections = require('../base').Collections;

  wave_demo = function(div_id) {
    var bars, colors, source, val, x, xdr, xs, ydr, ys;
    xs = (function() {
      var _i, _len, _ref, _results;
      _ref = _.range(630);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        x = _ref[_i];
        _results.push(x / 50);
      }
      return _results;
    })();
    ys = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = xs.length; _i < _len; _i++) {
        x = xs[_i];
        _results.push(Math.sin(x));
      }
      return _results;
    })();
    colors = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = ys.length; _i < _len; _i++) {
        val = ys[_i];
        _results.push("rgb(" + (Math.floor(155 + 100 * val)) + ", " + (Math.floor(100 + 50 * val)) + ", " + (Math.floor(150 - 50 * val)) + ")");
      }
      return _results;
    })();
    source = Collections('ColumnDataSource').create({
      data: {
        x: xs,
        y: ys,
        fill: colors
      }
    });
    xdr = Collections('DataRange1d').create({
      sources: [
        {
          ref: source.ref(),
          columns: ['x']
        }
      ]
    });
    ydr = Collections('DataRange1d').create({
      sources: [
        {
          ref: source.ref(),
          columns: ['y']
        }
      ]
    });
    bars = {
      x: 'x',
      y: 'y',
      width: 0.01,
      height: 0.4,
      type: 'rect',
      fill_color: 'fill',
      line_color: null,
      angle: 0.1
    };
    return this.make_plot(div_id, source, {}, [bars], xdr, ydr, {
      dims: [600, 600],
      plot_title: "",
      legend: false
    });
  };

  this.wave_demo = wave_demo;

}).call(this);
